# Generated by Django 4.2 on 2023-04-12 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelloapp', '0004_alter_guest_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='img',
            field=models.ImageField(upload_to='guest'),
        ),
    ]
