# Generated by Django 4.2 on 2023-04-12 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelloapp', '0005_alter_guest_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('img', models.ImageField(upload_to='people')),
                ('desc', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Guest',
        ),
    ]
